name: Deploy container to ghcr

on: 
  push:
    tags:
    - 'v*'
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github actions
        uses: actions/checkout@main
      
      - name: Get tag name
        id: get_tag_name  
        run: echo "::set-output name=tag::$(echo "${{ github.ref }}" | grep -oP 'refs/tags/\K(.+)')"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          imageName: ghcr.io/uol-feps-soc-2023internprojects/microbit-devcontainer
          push: always
          # Change this to be your CI task/script
          runCmd: |
            # Add multiple commands to run if needed
            make install-packages
            make ci-build



          
  
